# Run docker-compose build
# Run docker-compose up --no-recreate
# docker exec -it -u root <host-container-id> /bin/bash
# docker inspect <container id>
# docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
# Live long and prosper

version: '2'

services:



#http://localhost:8010/website/
  host: 
    container_name: sf-host-node
    image: sf-host-node
    build:
      context: .
      dockerfile: ./IAB-sf-host/Dockerfile
    ports:
      - "8010:8010"
      - "8011:8011"
    networks:
      - safeframe-network
    environment:
      - VIRTUAL_HOST=safeframe-host.localhost

  ads:
    container_name: sf-ads-node
    image: sf-ads-node
    build:
      context: .
      dockerfile: ./IAB-sf-ads/Dockerfile
    ports:
      - "8020:8020"
      - "8021:8021"
    networks:
      - safeframe-network
    environment:
      - VIRTUAL_HOST=safeframe-ads.localhost


  whoami:
    image: jwilder/whoami
    container_name: sf-whoami
    environment:
      - VIRTUAL_HOST=whoami.localhost
    networks:
      - safeframe-network

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: sf-nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - safeframe-network

networks:
  safeframe-network:
    driver: bridge