# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '2'

services:

  sf-host:
    container_name: sf-host
    image: sf-host
    build:
      context: .
      dockerfile: ./IAB-sf-host/Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "8010:8010"
      - "8011:8011"
    networks:
      - safeframe-test

  sf-ads:
    container_name: sf-ads
    image: sf-ads
    build:
      context: .
      dockerfile: ./IAB-sf-ads/Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "8020:8020"
      - "8021:8021"
    networks:
      - safeframe-test
      
networks:
  safeframe-test:
    driver: bridge